version: "3.5"

services:
  node1:
    image: dconnolly/bitcoin-cash:abc-0.17
    volumes:
      - data1:/data
    networks:
      - bchnet
    ports:
      - target: 18333
        published: 18333
        protocol: tcp
        mode: host
      - target: 18332
        published: 18332
        protocol: tcp
        mode: host
    configs:
      - source: bchconfinit
        target: /data/bitcoin.conf
    secrets:
      - bchrpcuser
      - bchrpcpassword
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 300s

networks:
  bchnet:
    driver: overlay

volumes:
  data1:

secrets:
  bchrpcuser:
    external: true
  bchrpcpassword:
    external: true

configs:
  bchconfinit:
    file: ./init.conf

